clone_depth: 10

# Needs this for most recent MSYS
image: Visual Studio 2022

cache:
  - C:\msys64\var\cache\pacman

install:
  - C:\msys64\usr\bin\bash.exe --login -c "pacman -Syu --noconfirm"
  - C:\msys64\usr\bin\bash.exe --login -c "pacman -S --noconfirm --needed git"
  - C:\msys64\usr\bin\bash.exe --login -c "pacman -S --noconfirm --needed openssl"
  - C:\msys64\usr\bin\bash.exe --login -c "pacman -S --noconfirm --needed p7zip"
  - C:\msys64\usr\bin\bash.exe --login -c "curl -L -o 7zsd_extra_170_3900.7z https://github.com/chrislake/7zsfxmm/releases/download/1.7.0.3900/7zsd_extra_170_3900.7z"
  - C:\msys64\usr\bin\bash.exe --login -c "TARGET_DIR=`cd $APPVEYOR_BUILD_FOLDER && pwd` && mkdir $TARGET_DIR/7zsd_extra && 7z e 7zsd_extra_170_3900.7z -o$TARGET_DIR/7zsd_extra"

build_script:
  - C:\msys64\usr\bin\bash.exe --login -c "cd $APPVEYOR_BUILD_FOLDER && ./release.sh"

artifacts:
  - path: uit-thesis-install.exe
    name: installer
    type: file

# https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
on_failure:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
